### ISSUE TITLE
Team 126-Kermits

### ISSUE THREAD

**Issue by Srjnnnn** [defoebrand/enumerables#2]
Instead of a class check, you can use the "is_a?" attribute.
You can use "is_a?" for self-checks without mentioning the self.
The way you use your methods again is very cool.
You can refactor your "my inject" with putting arguments condition on top and you can make the code more readable.

**Comment by defoebrand** [comment]
is_a? tested and failed some tests so it will be ignored until further understanding of why those tests fail
my_inject made more readable by the inclusion of variables
